spring:
  application:
    name: service-auth
  redis:
    database: 0
    host: 180.76.248.216
    port: 6379
    password: 123456
  datasource:
    username: root
    password: root
    #同样 低版本的MySql不需要指定时区
    url: jdbc:mysql://180.76.248.216:3306/oa-oauth?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    #mysql8.0以后的加密方式为caching_sha2_password，所以必须用com.mysql.cj.jdbc.Driver,前提是pom里引入的mysql-connector-java必须为8.0.12的，8.0.13不行，会报错
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

info:
  app.name: oa-oauth-server
  company.name: com.ly

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
  instance:
    instance-id: oa-oauth-server


logging:
  level:
    com.ly.oa: debug