server:
  port: 6661

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
  instance:
    instance-id: oa-user-server-edge
    prefer-ip-address: true

info:
  app.name: oa-user-server-edge
  company.name: com.ly

spring:
  application:
    name: oa-user-server-edge

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  client:
    config:
      oa-user-server:
        loggerLevel: full

management:
  server:
    port: 6661
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: "/actuator"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ly.oa.user.server.api: debug
